name: Tidy document
on:
  workflow_dispatch: {}
  push:
    branches:
      - gh-pages

jobs:
  tidy:
    name: Tidy up
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: brew install tidy-html5
      - run: tidy -config tidyconfig.txt -o index.html index.html
      - uses: peter-evans/create-pull-request@v3
        with:
          title: "chore(tidy): tidy up document"
          commit-message: "Tidied up document using tidy-html5"
          branch: html-tidy
          # A custom token is needed to trigger further workflow runs
          # https://github.com/peter-evans/create-pull-request/blob/master/docs/concepts-guidelines.md#triggering-further-workflow-runs
          token: ${{ secrets.GH_TOKEN }}
